#!/usr/bin/env bash
#The run install deleted .zsh-dotfile, this will re-clone if needed
#
# curl -sL https://raw.githubusercontent.com/bkmo/.zsh-dotfiles/master/.zsh-dotfiles/clone | bash
#
############
git clone --bare -b master https://github.com/bkmo/.zsh-dotfiles.git $HOME/.zsh-dotfiles

# define config alias locally since the dotfiles
# aren't installed on the system yet, then clone .zsh-dotfiles repo
function config {
   git --git-dir=$HOME/.zsh-dotfiles/ --work-tree=$HOME $@
}

config checkout -f
config config --local status.showUntrackedFiles no

