#!/usr/bin/env bash
# The script will attempt to install Git, Zsh and Pfetch as these packages along with the required fonts are required.
# Select the MesloLGS NF font as your terminal font
# additionally yay and pacman-contrib will be installed on Arch derivatives.
#
# Execute one of these commands in your terminal to run the script.
#
# curl -sL https://bit.ly/3CWMwie | bash
#
# OR
#
# bash -c "$(curl -sL https://bit.ly/3CWMwie)"
#
# OR
#
# curl -sL https://raw.githubusercontent.com/bkmo/.zsh-dotfiles/master/.zsh-dotfiles/run | bash
#
# install needed packages based on distro package manager
packagesNeeded='git zsh grc'
pkgsarch='git zsh grc pacman-contrib'

if [ -x "$(command -v pacman)" ]; then sudo pacman --noconfirm -Sy $pkgsarch
elif [ -x "$(command -v apt)" ]; then sudo apt -y install $packagesNeeded
elif [ -x "$(command -v dnf)" ]; then sudo dnf install $packagesNeeded
elif [ -x "$(command -v zypper)" ]; then sudo zypper install $packagesNeeded
else echo "FAILED TO INSTALL PACKAGES: Package manager not found. You must manually install: $packagesNeeded">&2; fi

echo
echo
echo "Pausing to see if there are any Package Manager errors"
echo
sleep 5s
clear

git clone --bare -b master https://github.com/bkmo/.zsh-dotfiles.git $HOME/.zsh-dotfiles

echo "alias config='/usr/bin/git --git-dir=$HOME/.zsh-dotfiles/ --work-tree=$HOME'" >> $HOME/.bashrc

# define config alias locally since the dotfiles
# aren't installed on the system yet, then clone .zsh-dotfiles repo
function config {
   git --git-dir=$HOME/.zsh-dotfiles/ --work-tree=$HOME $@
}

config checkout -f
config config --local status.showUntrackedFiles no

cp -fv ~/.config/zsh/.zsh_history-saved ~/.config/zsh/.zsh_history

#install yay from binary package
if [ -x "$(command -v pacman)" ] && ! builtin type -p 'yay' >/dev/null 2>&1; then
    sudo pacman --noconfirm -U ~/.config/zsh/pkg/yay-bin-11.3.0-1-x86_64.pkg.tar.zst
fi

#install clean_package_cache.hook arch/pacman
if [ -x "$(command -v pacman)" ] ; then
    sudo install -m 644 -D ~/.local/bin/clean_package_cache.hook /etc/pacman.d/hooks/clean_package_cache.hook
fi

#install Konsole configs
install -m 644 -D ~/.config/zsh/konsole/Profile\ 1.profile ~/.local/share/konsole/Profile\ 1.profile
install -m 644 -D ~/.config/zsh/konsole/Breeze.colorscheme ~/.local/share/konsole/Breeze.colorscheme
install -m 644 -D ~/.config/zsh/konsole/konsolerc ~/.config/konsolerc

#delete, we are done with them
rm -rf ~/.zsh-dotfiles

clear
echo
echo
echo
echo Answer yes '"y"' when asked to change your login shell to zsh
echo
echo
echo Make sure to change your terminal font to MesloLGS NF and logout/login
echo
echo
sleep 5s

source ~/.zshenv
